spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=jwt_security;trustServerCertificate=true
    username: sa
    password: lekhuonghau
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
